const {chromium}=await import('playwright').catch(()=>import(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright/index.mjs'));
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {testData,testFixture} from './helpers.js';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']}),errors=[];
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8080/');await page.getByRole('heading',{name:'Results',exact:true}).waitFor();assert.equal(await page.title(),'ATP Cup');
for(const path of ['standings','ratings','teams','fixtures','results']){await page.goto('http://127.0.0.1:8080/#/'+path);await page.locator('h1').first().waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+path);}
fs.mkdirSync('/tmp/atp-cup-qa',{recursive:true});await page.goto('http://127.0.0.1:8080/#/results');await page.screenshot({path:'/tmp/atp-cup-qa/desktop.png',fullPage:true});
await page.getByRole('button',{name:'Manual data',exact:true}).click();await page.getByRole('button',{name:'Data & rules',exact:true}).click();const data=testData(),future=testFixture();future.rubbers=[];future.squads={home:[],away:[]};future.status='scheduled';data.fixtures=[future];
await page.locator('#import-data').setInputFiles({name:'test-events.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.getByText('Local draft',{exact:true}).waitFor();await page.getByRole('button',{name:'Fixture editor',exact:true}).click();await page.locator('[name="edit-fixture"]').selectOption('test-r1');
for(const side of ['home','away'])for(let i=0;i<8;i++)await page.locator(`[name="squad-${side}"][value="${side==='home'?'a':'b'}${i}"]`).check();
for(let n=1;n<=8;n++){const doubles=n>4;for(const side of ['home','away'])for(let j=0;j<(doubles?2:1);j++)await page.locator(`[name="${side}-${n}-${j}"]`).selectOption((side==='home'?'a':'b')+(doubles?(n-5)*2+j:n-1));await page.locator(`[name="score-${n}"]`).fill(n===5?'6-4 3-6 [10-7]':'6-4 6-4');}
await page.locator('[name="status"]').selectOption('completed');await page.getByRole('button',{name:'Review calculations',exact:true}).click();await page.getByRole('button',{name:'Save local data',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('atp-cup-admin-draft-v1')).fixtures[0].status==='completed',{},{timeout:5000});await page.waitForTimeout(200);
await page.goto('http://127.0.0.1:8080/#/standings');await page.locator('#main h1').first().waitFor();assert.match(await page.locator('#main tbody').innerText(),/3/);await page.goto('http://127.0.0.1:8080/#/results');await page.locator('.fixture-card').first().click();await page.locator('#detail:not(.hidden)').waitFor();assert.match(await page.locator('#detail-body').innerText(),/8–0/);assert.match(await page.locator('#detail-body').innerText(),/95–66/);await page.screenshot({path:'/tmp/atp-cup-qa/match-desktop.png',fullPage:true});
await page.goto('http://127.0.0.1:8080/#/player/a0');await page.getByRole('heading',{name:/Test player a0/}).waitFor();assert.match(await page.locator('#detail-body').innerText(),/2–0/);await page.goto('http://127.0.0.1:8080/#/ratings');await page.locator('#main tbody').waitFor();assert.equal(await page.locator('#main tbody tr').count(),8);
await page.reload();await page.locator('#main tbody').waitFor();assert.equal(await page.locator('#main tbody tr').count(),8,'draft survives reload');
await page.getByRole('button',{name:'Manual data',exact:true}).click();await page.getByRole('button',{name:'Data & rules',exact:true}).click();const dlPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export JSON',exact:true}).click();const download=await dlPromise;const content=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(content.fixtures[0].rubbers[4].matchTiebreak.home,10);assert.equal(content.fixtures[0].rubbers[4].sets.length,2);
await page.getByRole('button',{name:'Manual data',exact:true}).click();await page.getByRole('button',{name:'Fixture editor',exact:true}).click();await page.locator('[name="edit-fixture"]').selectOption('test-r1');await page.locator('[name="score-1"]').fill('6-4 3-6 6-4');await page.getByRole('button',{name:'Save local data',exact:true}).click();await page.getByText('Local data saved. All derived views rebuilt.',{exact:true}).waitFor();await page.goto('http://127.0.0.1:8080/#/fixture/test-r1');await page.locator('#detail:not(.hidden)').waitFor();assert.match(await page.locator('#detail-body').innerText(),/98–72/);
await page.setViewportSize({width:390,height:844});for(const path of ['standings','ratings','teams','fixtures','results']){await page.goto('http://127.0.0.1:8080/#/'+path);await page.locator('h1').first().waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile overflow '+path);}
await page.goto('http://127.0.0.1:8080/#/results');await page.screenshot({path:'/tmp/atp-cup-qa/mobile.png',fullPage:true});await page.goto('http://127.0.0.1:8080/#/fixture/test-r1');await page.locator('#detail:not(.hidden)').waitFor();assert.equal(await page.locator('#detail').evaluate(el=>el.scrollWidth>el.clientWidth),false,'match modal mobile overflow');assert.equal(await page.locator('#detail').evaluate(el=>Math.abs(el.getBoundingClientRect().top)<1),true,'mobile modal anchored to viewport');await page.screenshot({path:'/tmp/atp-cup-qa/match-mobile.png'});await page.keyboard.press('Escape');assert.equal(await page.locator('#detail').evaluate(el=>el.classList.contains('hidden')),true);
await page.goto('http://127.0.0.1:8080/#/player/a0');await page.locator('#detail:not(.hidden)').waitFor();assert.equal(await page.locator('#detail').evaluate(el=>el.scrollWidth>el.clientWidth),false,'player lab mobile overflow');await page.goto('http://127.0.0.1:8080/#/team/a');await page.locator('#detail:not(.hidden)').waitFor();assert.equal(await page.locator('#detail').evaluate(el=>el.scrollWidth>el.clientWidth),false,'team mobile overflow');
await page.getByRole('button',{name:'Manual data',exact:true}).click();await page.getByRole('button',{name:'Players',exact:true}).click();await page.locator('[name="fullName"]').fill('Administrator supplied player');await page.locator('[name="nationality"]').fill('Administrator supplied nation');await page.getByRole('button',{name:'Save player',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('atp-cup-admin-draft-v1')).players.some(p=>p.fullName==='Administrator supplied player'));await page.getByRole('button',{name:'Data & rules',exact:true}).click();const previous=await page.evaluate(()=>localStorage.getItem('atp-cup-admin-draft-v1'));await page.locator('#import-data').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":0}')});await page.getByText(/Expected an ATP Cup data package/).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('atp-cup-admin-draft-v1')),previous,'invalid import leaves data intact');
assert.deepEqual(errors,[]);await browser.close();console.log('Desktop/mobile navigation, manual fixture entry, downstream propagation, score correction, profile/table layout, import/export and reload persistence passed.');
