const {chromium}=await import('playwright').catch(()=>import(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright/index.mjs'));
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {testData,testFixture} from './helpers.js';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']}),errors=[];
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8080/');await page.getByRole('heading',{name:'Results',exact:true}).waitFor();assert.equal(await page.title(),'ATP Cup');
for(const path of ['standings','ratings','teams','fixtures','results']){await page.goto('http://127.0.0.1:8080/#/'+path);await page.locator('h1').first().waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+path);}
fs.mkdirSync('/tmp/atp-cup-qa',{recursive:true});await page.goto('http://127.0.0.1:8080/#/results');await page.screenshot({path:'/tmp/atp-cup-qa/desktop.png',fullPage:true});
await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('heading',{name:'Settings',exact:true}).waitFor();await page.getByRole('button',{name:'Dark',exact:true}).waitFor();await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Manual data',exact:true}).click();await page.getByRole('button',{name:'Data & rules',exact:true}).click();const templateDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Download setup workbook'}).click();assert.match((await templateDownload).suggestedFilename(),/setup workbook\.xlsx$/i);const guideDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Download the plain-language guide'}).click();assert.match((await guideDownload).suggestedFilename(),/setup guide\.txt$/i);const exampleDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Download example workbook',exact:true}).click();assert.match((await exampleDownload).suggestedFilename(),/example workbook\.xlsx$/i);await page.locator('#setup-workbook').setInputFiles('assets/atp-cup-setup-example.xlsx');await page.getByText('Your workbook is ready to review.',{exact:true}).waitFor();assert.match(await page.locator('.setup-review').innerText(),/3 teams · 5 players · 1 season/);assert.equal(await page.getByRole('button',{name:'Apply this setup',exact:true}).count(),1);assert.equal(await page.evaluate(()=>localStorage.getItem('atp-cup-admin-draft-v1')),null,'example preview must not save');await page.locator('#setup-workbook').setInputFiles('assets/atp-cup-setup.xlsx');await page.getByText(/18 teams · 0 players · 1 season/).waitFor();assert.match(await page.locator('.setup-review').innerText(),/18 teams · 0 players · 1 season/);assert.equal(await page.getByRole('button',{name:'Apply this setup'}).count(),1);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('atp-cup-admin-draft-v1')||'null')),null,'review must not save before confirmation');await page.getByRole('button',{name:'Apply this setup',exact:true}).click();await page.getByText('Setup imported. Any match results already on this site were kept.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('atp-cup-admin-draft-v1')).teams.length),18);
const data=testData(),future=testFixture();future.rubbers=[];future.squads={home:[],away:[]};future.status='scheduled';data.fixtures=[future];
await page.locator('#import-data').setInputFiles({name:'test-events.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.getByText('Local draft',{exact:true}).waitFor();await page.getByRole('button',{name:'Fixture editor',exact:true}).click();await page.locator('[name="edit-fixture"]').selectOption('test-r1');
for(const side of ['home','away'])for(let i=0;i<8;i++)await page.locator(`[name="squad-${side}"][value="${side==='home'?'a':'b'}${i}"]`).check();
assert.equal(await page.locator('.fixture-details').getAttribute('open'),null,'scheduled details stay tucked away');
assert.equal(await page.locator('[name="squad-home"][value="a8"]').isDisabled(),true,'squad selection stops at eight');
assert.equal(await page.locator('.set-score-grid').count(),8);
async function fillGrid(num,cells){for(let set=0;set<3;set++)for(const [side,k] of [['home',0],['away',1]])await page.locator(`[name="score-${num}-${side}-${set}"]`).fill(cells[set]?.[k]??'');}
for(let n=1;n<=8;n++){const doubles=n>4;for(const side of ['home','away'])for(let j=0;j<(doubles?2:1);j++){const id=(side==='home'?'a':'b')+(doubles?(n-5)*2+j:n-1);if(!doubles)await page.locator(`[name="${side}-${n}-${j}"]`).selectOption(id);else{const field=page.locator(`[data-player-key="${side}-${n}-${j}"]`);await field.fill(id);assert.equal(await page.locator(`#options-${side}-${n}-${j} [role="option"]`).count(),1);if(n===5&&side==='home'&&j===0){await field.press('ArrowDown');await page.keyboard.press('Enter');}else await page.locator(`#options-${side}-${n}-${j} [data-player="${id}"]`).click();assert.equal(await page.locator(`[name="${side}-${n}-${j}"]`).inputValue(),id);}}await fillGrid(n,n===5?[['6','4'],['3','6'],['10','7']]:[['6','4'],['6','4']]);}
// Score entry automatically derives winners and completed status. Changing the squad retains draft scores.
await page.locator('[name="squad-home"][value="a7"]').uncheck();assert.equal(await page.locator('[name="home-8-1"]').inputValue(),'','removed players are cleared from pairs');assert.equal(await page.locator('[name="score-5-home-2"]').inputValue(),'10');await page.locator('[name="squad-home"][value="a7"]').check();await page.locator('[data-player-key="home-8-1"]').fill('a7');await page.locator('#options-home-8-1 [data-player="a7"]').click();
await page.locator('[data-player-key="home-5-0"]').fill('unknown name');assert.equal(await page.locator('[name="home-5-0"]').inputValue(),'','free text never acts as a selected player');assert.equal(await page.locator('#options-home-5-0 [role="option"]').count(),0);await page.locator('[data-player-key="home-5-0"]').fill('a0');await page.locator('#options-home-5-0 [data-player="a0"]').click();
await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('#detail').evaluate(el=>el.scrollWidth>el.clientWidth),false,'fixture entry fits mobile');await page.locator('.rubber-editor').nth(4).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/atp-cup-qa/fixture-entry-mobile.png'});await page.setViewportSize({width:1440,height:1000});await page.locator('.rubber-editor').nth(4).scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/atp-cup-qa/fixture-entry-desktop.png'});
await page.getByRole('button',{name:'Review calculations',exact:true}).click();await page.getByRole('button',{name:'Save match results',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('atp-cup-admin-draft-v1')).fixtures[0].status==='completed',{},{timeout:5000});await page.waitForTimeout(200);const entered=await page.evaluate(()=>JSON.parse(localStorage.getItem('atp-cup-admin-draft-v1')).fixtures[0]);assert.equal(entered.date,future.date);assert.equal(entered.venue,future.venue);assert.equal(entered.surface,future.surface);assert.equal(entered.rubbers[0].sets.length,2);assert.deepEqual(entered.rubbers[4].matchTiebreak,{home:10,away:7});
await page.goto('http://127.0.0.1:8080/#/standings');await page.locator('#main h1').first().waitFor();assert.match(await page.locator('#main tbody').innerText(),/3/);await page.goto('http://127.0.0.1:8080/#/results');await page.locator('.fixture-card').first().click();await page.locator('#detail:not(.hidden)').waitFor();assert.match(await page.locator('#detail-body').innerText(),/8–0/);assert.match(await page.locator('#detail-body').innerText(),/95–66/);await page.screenshot({path:'/tmp/atp-cup-qa/match-desktop.png',fullPage:true});
await page.goto('http://127.0.0.1:8080/#/player/a0');await page.getByRole('heading',{name:/Test player a0/}).waitFor();assert.match(await page.locator('#detail-body').innerText(),/2–0/);await page.goto('http://127.0.0.1:8080/#/ratings');await page.locator('#main tbody').waitFor();assert.equal(await page.locator('#main tbody tr').count(),8);
await page.reload();await page.locator('#main tbody').waitFor();assert.equal(await page.locator('#main tbody tr').count(),8,'draft survives reload');
await page.getByRole('button',{name:'Manual data',exact:true}).click();await page.getByRole('button',{name:'Data & rules',exact:true}).click();await page.locator('.advanced-tools > summary').click();const dlPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download full-data file',exact:true}).click();const download=await dlPromise;const content=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(content.fixtures[0].rubbers[4].matchTiebreak.home,10);assert.equal(content.fixtures[0].rubbers[4].sets.length,2);await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Manual data',exact:true}).click();await page.getByRole('button',{name:'Fixture editor',exact:true}).click();await page.locator('[name="edit-fixture"]').selectOption('test-r1');await fillGrid(1,[['6','4'],['3','6'],['6','4']]);await page.getByRole('button',{name:'Save match results',exact:true}).click();await page.getByText('Local data saved. All derived views rebuilt.',{exact:true}).waitFor();await page.goto('http://127.0.0.1:8080/#/fixture/test-r1');await page.locator('#detail:not(.hidden)').waitFor();assert.match(await page.locator('#detail-body').innerText(),/98–72/);
await page.setViewportSize({width:390,height:844});for(const path of ['standings','ratings','teams','fixtures','results']){await page.goto('http://127.0.0.1:8080/#/'+path);await page.locator('h1').first().waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile overflow '+path);}
await page.goto('http://127.0.0.1:8080/#/results');await page.screenshot({path:'/tmp/atp-cup-qa/mobile.png',fullPage:true});await page.goto('http://127.0.0.1:8080/#/fixture/test-r1');await page.locator('#detail:not(.hidden)').waitFor();assert.equal(await page.locator('#detail').evaluate(el=>el.scrollWidth>el.clientWidth),false,'match modal mobile overflow');assert.equal(await page.locator('#detail').evaluate(el=>Math.abs(el.getBoundingClientRect().top)<1),true,'mobile modal anchored to viewport');await page.screenshot({path:'/tmp/atp-cup-qa/match-mobile.png'});await page.keyboard.press('Escape');assert.equal(await page.locator('#detail').evaluate(el=>el.classList.contains('hidden')),true);
await page.goto('http://127.0.0.1:8080/#/player/a0');await page.locator('#detail:not(.hidden)').waitFor();assert.equal(await page.locator('#detail').evaluate(el=>el.scrollWidth>el.clientWidth),false,'player lab mobile overflow');await page.goto('http://127.0.0.1:8080/#/team/a');await page.locator('#detail:not(.hidden)').waitFor();assert.equal(await page.locator('#detail').evaluate(el=>el.scrollWidth>el.clientWidth),false,'team mobile overflow');await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Manual data',exact:true}).click();await page.getByRole('button',{name:'Players',exact:true}).click();await page.locator('[name="fullName"]').fill('Administrator supplied player');await page.locator('[name="nationality"]').fill('Administrator supplied nation');await page.getByRole('button',{name:'Save player',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('atp-cup-admin-draft-v1')).players.some(p=>p.fullName==='Administrator supplied player'));await page.getByRole('button',{name:'Data & rules',exact:true}).click();const previous=await page.evaluate(()=>localStorage.getItem('atp-cup-admin-draft-v1'));await page.locator('#import-data').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":0}')});await page.getByText(/Expected an ATP Cup data package/).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('atp-cup-admin-draft-v1')),previous,'invalid import leaves data intact');
await page.getByRole('button',{name:'Fixture editor',exact:true}).click();await page.locator('[name="edit-fixture"]').selectOption('test-r1');const beforeBadScore=await page.evaluate(()=>localStorage.getItem('atp-cup-admin-draft-v1'));await page.locator('[name="score-1-away-0"]').fill('');await page.getByRole('button',{name:'Save match results',exact:true}).click();await page.locator('#live-review').getByText(/Enter both teams/).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('atp-cup-admin-draft-v1')),beforeBadScore,'an incomplete score grid cannot overwrite saved results');
await fillGrid(1,[['6','4'],['2','1']]);await page.locator('.rubber-editor').first().locator('.match-exceptions > summary').click();await page.locator('[name="status-1"]').selectOption('retirement');await page.locator('[name="winner-1"]').selectOption('home');await page.getByRole('button',{name:'Save match results',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('atp-cup-admin-draft-v1')).fixtures[0].rubbers[0].status==='retirement');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('atp-cup-admin-draft-v1')).fixtures[0].rubbers[0].sets[1].complete),false);
await page.locator('.rubber-editor').first().locator('.match-exceptions > summary').click();await fillGrid(1,[]);await page.locator('[name="status-1"]').selectOption('walkover');await page.locator('[name="winner-1"]').selectOption('away');await page.getByRole('button',{name:'Save match results',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('atp-cup-admin-draft-v1')).fixtures[0].rubbers[0].status==='walkover');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('atp-cup-admin-draft-v1')).fixtures[0].rubbers[0].sets.length),0);
assert.deepEqual(errors,[]);await browser.close();console.log('Desktop/mobile navigation, squad selection, fuzzy doubles search, set grids, automatic status, draft preservation, score corrections, exceptional outcomes, import/export and reload persistence passed.');
