import {rulesFor,rosterFor,pairKey,fixtureDefaults} from './config.js';
import {fixtureResult,scoreTotals} from './scores.js';
import {allRatings} from './ratings.js';
const blank=()=>({played:0,wins:0,draws:0,losses:0,rubbersFor:0,rubbersAgainst:0,setsFor:0,setsAgainst:0,gamesFor:0,gamesAgainst:0,points:0,form:[],home:{wins:0,draws:0,losses:0},away:{wins:0,draws:0,losses:0},surfaces:{},opponents:{},singlesWins:0,doublesWins:0});
export function eventLog(data,seasonId,{career=false}={}) {return data.fixtures.filter(f=>f.status==='completed'&&(career||f.seasonId===seasonId)).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id)).flatMap(raw=>{const f=fixtureDefaults(data,raw);return (f.rubbers||[]).slice().sort((a,b)=>a.rubberNumber-b.rubberNumber).map(rubber=>({fixtureId:f.id,seasonId:f.seasonId,date:f.date,surface:f.surface,stage:f.stage,homeTeamId:f.homeTeamId,awayTeamId:f.awayTeamId,home:rubber.homePlayers,away:rubber.awayPlayers,winner:rubber.winner,rubber}));});}
export function standings(data,seasonId) {const season=data.seasons.find(s=>s.id===seasonId),rules=rulesFor(data,seasonId),table=Object.fromEntries((season?.teamIds||[]).map(id=>[id,{teamId:id,...blank()}]));for(const f of data.fixtures.filter(f=>f.seasonId===seasonId&&f.stage==='regular'&&f.status==='completed').sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id))){const t=fixtureResult(f,rules);if(!t.complete)continue;for(const [i,id] of [f.homeTeamId,f.awayTeamId].entries()){const s=table[id];if(!s)continue;const result=t.draw?'draws':t.winner===(i===0?'home':'away')?'wins':'losses';s.played++;s[result]++;s.points+=rules.points[result==='wins'?'win':result==='draws'?'draw':'loss'];for(const [key,arr] of [['rubbers',t.rubbers],['sets',t.sets],['games',t.games]]){s[key+'For']+=arr[i];s[key+'Against']+=arr[1-i];}s.form.push(result==='wins'?'W':result==='draws'?'D':'L');s[i===0?'home':'away'][result]++;}}
 const sorted=Object.values(table).map(s=>({...s,rubberDiff:s.rubbersFor-s.rubbersAgainst,setDiff:s.setsFor-s.setsAgainst,gameDiff:s.gamesFor-s.gamesAgainst})).sort((a,b)=>{for(const key of rules.standingsTiebreaks){const d=b[key]-a[key];if(d)return d;}return a.teamId.localeCompare(b.teamId);});sorted.forEach((s,i)=>{s.position=i+1;s.tied=sorted.some(t=>t!==s&&rules.standingsTiebreaks.every(k=>t[k]===s[k]));});return sorted;}
export function finalHost(season,rules) {const cycle=season.finals?.cycle;if(!cycle)return null;const order=rules.finals.finalHostOrder,key=order[(season.year-cycle.startYear)%order.length];return cycle['host'+key]||null;}
export function finalsBracket(data,seasonId,table=standings(data,seasonId)) {const season=data.seasons.find(s=>s.id===seasonId),rules=rulesFor(data,seasonId),regular=data.fixtures.filter(f=>f.seasonId===seasonId&&f.stage==='regular'&&f.status!=='cancelled'),expected=season.teamIds.length*(season.teamIds.length-1),complete=regular.length===expected&&regular.every(f=>f.status==='completed'),boundaryTie=table[rules.finalsTeams-1]&&table[rules.finalsTeams]&&rules.standingsTiebreaks.every(k=>table[rules.finalsTeams-1][k]===table[rules.finalsTeams][k]);
 const seeds=season.finals?.seeds||(complete&&!boundaryTie?table.slice(0,rules.finalsTeams).map(t=>t.teamId):null),projected=seeds||table.slice(0,rules.finalsTeams).map(t=>t.teamId),fixtures=data.fixtures.filter(f=>f.seasonId===seasonId&&f.stage!=='regular'),win=f=>f&&f.status==='completed'?(fixtureResult(f,rules).winner==='home'?f.homeTeamId:fixtureResult(f,rules).winner==='away'?f.awayTeamId:null):null;
 const find=(stage,slot)=>fixtures.find(f=>f.stage===stage&&f.bracketSlot===slot),q=rules.finals.quarterfinalSeeds.map(([a,b],i)=>({slot:i+1,home:projected[a-1],away:projected[b-1],seeds:[a,b],fixture:find('quarterfinal',i+1)})),sf=[0,1].map(i=>({slot:i+1,home:win(q[i*2]?.fixture),away:win(q[i*2+1]?.fixture),fixture:find('semifinal',i+1)})),final={slot:1,home:win(sf[0]?.fixture),away:win(sf[1]?.fixture),fixture:find('final',1)};
 const bounds=table.map(t=>{const remaining=regular.filter(f=>f.status!=='completed'&&[f.homeTeamId,f.awayTeamId].includes(t.teamId)).length;return {teamId:t.teamId,min:t.points+remaining*Math.min(...Object.values(rules.points)),max:t.points+remaining*Math.max(...Object.values(rules.points))};}),qualification=bounds.map(t=>{const above=bounds.filter(x=>x.teamId!==t.teamId&&x.min>t.max).length,canCatch=bounds.filter(x=>x.teamId!==t.teamId&&x.max>=t.min).length;return {teamId:t.teamId,status:seeds?(seeds.includes(t.teamId)?'Qualified':'Eliminated'):regular.length!==expected?'In contention':above>=rules.finalsTeams?'Eliminated':canCatch<rules.finalsTeams?'Clinched':'In contention'};});return {complete,locked:!!seeds,boundaryTie,projected:!seeds,seeds,quarterfinals:q,semifinals:sf,final,finalHost:finalHost(season,rules),qualification};}
function playerStats(events,id,rules){const s={matches:0,wins:0,losses:0,singles:{wins:0,losses:0},doubles:{wins:0,losses:0},setsFor:0,setsAgainst:0,gamesFor:0,gamesAgainst:0,appearances:0,home:{wins:0,losses:0},away:{wins:0,losses:0},surfaces:{},opponents:{},partners:{},form:[],log:[]},seen=new Set();for(const e of events){const side=e.home.includes(id)?'home':e.away.includes(id)?'away':null;if(!side)continue;const i=side==='home'?0:1,w=e.winner===side,t=scoreTotals(e.rubber,rules),result=w?'wins':'losses';s.matches++;s[result]++;s[e.rubber.type][result]++;s[side][result]++;s.setsFor+=t.sets[i];s.setsAgainst+=t.sets[1-i];s.gamesFor+=t.games[i];s.gamesAgainst+=t.games[1-i];s.form.push(w?'W':'L');seen.add(e.fixtureId);const split=s.surfaces[e.surface]||={wins:0,losses:0};split[result]++;for(const opponent of e[side==='home'?'away':'home']){(s.opponents[opponent]||={wins:0,losses:0})[result]++;}for(const partner of e[side].filter(p=>p!==id)){(s.partners[partner]||={wins:0,losses:0})[result]++;}s.log.push({...e,side,won:w});}s.appearances=seen.size;return s;}
export function derive(data,seasonId) {const season=data.seasons.find(s=>s.id===seasonId),rules=rulesFor(data,seasonId),events=eventLog(data,seasonId),cutoff=events.at(-1)?.date||season.endDate,career=eventLog(data,seasonId,{career:true}).filter(e=>e.date<=cutoff),ratings=allRatings(career,rules,{referenceDate:cutoff}),dates=[...new Set(career.map(e=>e.date))],history={},careerPeaks={};for(const date of dates){const snapshot=allRatings(career.filter(e=>e.date<=date),rules,{uncertainty:false,referenceDate:date});for(const id of Object.keys(snapshot.overall)){const peak=careerPeaks[id]||={singles:null,doubles:null};for(const mode of ['singles','doubles'])if(snapshot[mode][id])peak[mode]=Math.max(peak[mode]??-Infinity,snapshot[mode][id].rating);if(events.some(e=>e.date===date))(history[id]||=[]).push({date,singles:snapshot.singles[id]?.rating??null,doubles:snapshot.doubles[id]?.rating??null,overall:snapshot.overall[id]?.rating??null});}}
 const players=Object.fromEntries(data.players.map(p=>[p.id,playerStats(events,p.id,rules)])),careerPlayers=Object.fromEntries(data.players.map(p=>[p.id,playerStats(career,p.id,rules)])),table=standings(data,seasonId),teams={};for(const id of season.teamIds){const roster=rosterFor(data,seasonId,id,cutoff),mean=mode=>{const rs=roster.map(r=>ratings[mode][r.playerId]?.rating).filter(Number.isFinite);return rs.length?rs.reduce((s,v)=>s+v,0)/rs.length:null;},s=blank();for(const raw of data.fixtures.filter(f=>f.seasonId===seasonId&&f.status==='completed'&&[f.homeTeamId,f.awayTeamId].includes(id))){const f=fixtureDefaults(data,raw),t=fixtureResult(f,rules),side=id===f.homeTeamId?'home':'away',i=side==='home'?0:1;if(!t.winner&&!t.draw)continue;const result=t.draw?'draws':t.winner===side?'wins':'losses';s.played++;s[result]++;s[side][result]++;(s.surfaces[f.surface]||={wins:0,draws:0,losses:0})[result]++;(s.opponents[i===0?f.awayTeamId:f.homeTeamId]||={wins:0,draws:0,losses:0})[result]++;for(const r of f.rubbers)if(r.winner===side)s[r.type==='singles'?'singlesWins':'doublesWins']++;}teams[id]={...s,singlesStrength:mean('singles'),doublesStrength:mean('doubles'),overallStrength:mean('overall'),roster};}
 for(const id of season.teamIds){const fs=data.fixtures.filter(f=>f.seasonId===seasonId&&f.stage==='regular'&&[f.homeTeamId,f.awayTeamId].includes(id));for(const [key,predicate] of [['scheduleStrength',f=>f.status==='completed'],['remainingStrength',f=>f.status!=='completed']]){const vals=fs.filter(predicate).map(f=>teams[f.homeTeamId===id?f.awayTeamId:f.homeTeamId]?.overallStrength).filter(Number.isFinite);teams[id][key]=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;}}
 return {season,rules,events,ratings,history,careerPeaks,players,careerPlayers,standings:table,teams,finals:finalsBracket(data,seasonId,table)};
}
