import {pairKey} from './config.js';
import {scoreTotals} from './scores.js';
export const logistic=x=>1/(1+Math.exp(-Math.max(-40,Math.min(40,x))));
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
function cg(mul,b,diag){const n=b.length,x=Array(n).fill(0),r=[...b],z=r.map((v,i)=>v/diag[i]);let p=[...z],rz=dot(r,z);for(let k=0;k<Math.min(n*2,500)&&rz>1e-20;k++){const ap=mul(p),alpha=rz/dot(p,ap);for(let i=0;i<n;i++){x[i]+=alpha*p[i];r[i]-=alpha*ap[i];z[i]=r[i]/diag[i];}const next=dot(r,z),beta=next/rz;for(let i=0;i<n;i++)p[i]=z[i]+beta*p[i];rz=next;}return x;}
function inverseDiagonal(H){const n=H.length,L=Array.from({length:n},()=>Array(n).fill(0));for(let i=0;i<n;i++)for(let j=0;j<=i;j++){let s=H[i][j];for(let k=0;k<j;k++)s-=L[i][k]*L[j][k];L[i][j]=i===j?Math.sqrt(Math.max(s,1e-12)):s/L[j][j];}const out=[];for(let k=0;k<n;k++){const y=Array(n).fill(0);for(let i=k;i<n;i++){let s=i===k?1:0;for(let j=k;j<i;j++)s-=L[i][j]*y[j];y[i]=s/L[i][i];}out[k]=dot(y,y);}return out;}
function matrixRank(rows,n){const A=rows.map(r=>{const a=Array(n).fill(0);r.forEach(([i,c])=>a[i]+=c);return a;});let rank=0;for(let col=0;col<n&&rank<A.length;col++){let pivot=rank;while(pivot<A.length&&Math.abs(A[pivot][col])<1e-8)pivot++;if(pivot===A.length)continue;[A[pivot],A[rank]]=[A[rank],A[pivot]];const scale=A[rank][col];for(let j=col;j<n;j++)A[rank][j]/=scale;for(let i=rank+1;i<A.length;i++){const v=A[i][col];if(Math.abs(v)<1e-8)continue;for(let j=col;j<n;j++)A[i][j]-=v*A[rank][j];}rank++;}return rank;}
/** Sparse Newton / conjugate-gradient fit of the original regularised V3 score likelihood. */
export function fitRatings(events,mode,rules,{uncertainty=true,referenceDate}={}) {
 const cfg=rules.rating,valid=events.filter(e=>e.rubber.type===(mode==='singles'?'singles':'doubles')&&(e.rubber.status==='completed'||cfg.includeRetirements&&e.rubber.status==='retirement'));
 const side=e=>mode==='pairs'?[[pairKey(e.home)], [pairKey(e.away)]]:[e.home,e.away];
 const ids=[...new Set(valid.flatMap(e=>side(e).flat()))].sort(),n=ids.length;if(!n)return {};
 const ix=new Map(ids.map((p,i)=>[p,i])),reference=Date.parse(referenceDate||valid.at(-1).date),stats=Object.fromEntries(ids.map(id=>[id,{matches:0,wins:0,losses:0,gamesFor:0,gamesAgainst:0,partners:new Set()}]));
 const rows=valid.map(e=>{const [home,away]=side(e),t=scoreTotals(e.rubber,rules),weight=2**(-Math.max(0,(reference-Date.parse(e.date))/86400000)/cfg.halfLifeDays);for(const [i,list] of [home,away].entries())for(const id of list){const s=stats[id];s.matches++;s.wins+=e.winner===(i===0?'home':'away');s.losses+=e.winner!==(i===0?'home':'away');s.gamesFor+=t.games[i];s.gamesAgainst+=t.games[1-i];list.filter(p=>p!==id).forEach(p=>s.partners.add(p));}return {design:[...home.map(p=>[ix.get(p),1/home.length]),...away.map(p=>[ix.get(p),-1/away.length])],a:t.games[0],b:t.games[1],weight};});
 const theta=Array(n).fill(0),objective=x=>rows.reduce((s,r)=>{const z=r.design.reduce((v,[i,c])=>v+c*x[i],0)/cfg.scale;return s+r.weight*(r.a*Math.log(logistic(z))+r.b*Math.log(logistic(-z)));},-cfg.l2*dot(x,x)/2);
 let curvature=[];
 for(let step=0;step<40;step++){const grad=theta.map(v=>cfg.l2*v),diag=Array(n).fill(cfg.l2);curvature=rows.map(r=>{const p=logistic(r.design.reduce((v,[i,c])=>v+c*theta[i],0)/cfg.scale),z=-r.weight*(r.a-(r.a+r.b)*p)/cfg.scale,c=r.weight*(r.a+r.b)*p*(1-p)/cfg.scale**2;r.design.forEach(([i,a])=>{grad[i]+=z*a;diag[i]+=c*a*a;});return c;});if(Math.max(...grad.map(Math.abs))<1e-7)break;
 const mul=x=>{const out=x.map(v=>cfg.l2*v);rows.forEach((r,k)=>{const v=curvature[k]*r.design.reduce((v,[i,a])=>v+a*x[i],0);r.design.forEach(([i,a])=>out[i]+=a*v);});return out;},delta=cg(mul,grad,diag),old=objective(theta);let factor=1;while(factor>1e-7&&objective(theta.map((v,i)=>v-factor*delta[i]))<old)factor/=2;for(let i=0;i<n;i++)theta[i]-=factor*delta[i];}
 const mean=theta.reduce((a,b)=>a+b,0)/n;theta.forEach((_,i)=>theta[i]-=mean);
 let se=Array(n).fill(null),rank=null;
 if(uncertainty){const H=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j?cfg.l2:0));rows.forEach(r=>{const p=logistic(r.design.reduce((v,[i,c])=>v+c*theta[i],0)/cfg.scale),v=r.weight*(r.a+r.b)*p*(1-p)/cfg.scale**2;for(const [i,a] of r.design)for(const [j,b] of r.design)H[i][j]+=v*a*b;});se=inverseDiagonal(H).map(v=>cfg.displayScale*Math.sqrt(Math.max(0,v-1/(n*cfg.l2))));if(mode==='doubles')rank=matrixRank(rows.map(r=>r.design),n);}
 return Object.fromEntries(ids.map((id,i)=>{const s=stats[id],partners=[...s.partners],partnerDependent=mode==='doubles'&&(partners.length<2||rank!==null&&rank<n-1);return [id,{id,rating:cfg.centre+cfg.displayScale*theta[i],theta:theta[i],se:se[i],...s,partners,partnerDependent,provisional:s.matches<cfg.minMatches,networkRank:rank}];}));
}
export function allRatings(events,rules,options={}) {const singles=fitRatings(events,'singles',rules,options),doubles=fitRatings(events,'doubles',rules,options),pairs=fitRatings(events,'pairs',rules,options),overall={};for(const id of new Set([...Object.keys(singles),...Object.keys(doubles)])){const parts=[singles[id],doubles[id]].filter(Boolean),n=parts.length;overall[id]={id,rating:parts.reduce((s,r)=>s+r.rating,0)/n,se:parts.some(r=>r.se===null)?null:Math.sqrt(parts.reduce((s,r)=>s+r.se**2,0))/n,matches:parts.reduce((s,r)=>s+r.matches,0),wins:parts.reduce((s,r)=>s+r.wins,0),losses:parts.reduce((s,r)=>s+r.losses,0),gamesFor:parts.reduce((s,r)=>s+r.gamesFor,0),gamesAgainst:parts.reduce((s,r)=>s+r.gamesAgainst,0),provisional:parts.some(r=>r.provisional),coverage:n===2?'Singles + doubles':singles[id]?'Singles only':'Doubles only'};}return {singles,doubles,pairs,overall};}
