import {rulesFor,dateValid,rosterFor,fixtureDefaults} from './config.js';
import {parseScore,scoreText,fixtureResult} from './scores.js';
import {standings,finalsBracket,finalHost} from './derive.js';
export function audit(data,{strictSchedule=false}={}) {
 const errors=[],warnings=[],add=(path,message)=>errors.push({path,message}),warn=(path,message)=>warnings.push({path,message});
 if(!data||data.schemaVersion!==1)return {errors:[{path:'schemaVersion',message:'Expected an ATP Cup data package with schemaVersion 1.'}],warnings};
 for(const name of ['teams','players','seasons','rosters','fixtures'])if(!Array.isArray(data[name]))add(name,'Must be an array.');
 if(errors.length)return {errors,warnings};
 const maps={};for(const name of ['teams','players','seasons','fixtures']){maps[name]=new Map();for(const [i,row] of data[name].entries()){if(!row||typeof row.id!=='string'||!row.id.trim())add(`${name}[${i}]`,'A stable nonempty ID is required.');else if(!/^[A-Za-z0-9][A-Za-z0-9_-]*$/.test(row.id))add(`${name}[${i}]`,'IDs may contain letters, digits, hyphens and underscores only.');else if(maps[name].has(row.id))add(name,`Duplicate ID: ${row.id}.`);else maps[name].set(row.id,row);}}
 if(errors.length)return {errors,warnings};
 for(const t of data.teams){if(!t.name?.trim())add('team '+t.id,'Team name is required.');if(t.homeSurface&&!rulesFor(data,data.seasons[0]?.id).surfaces[t.homeSurface])add('team '+t.id,'Unknown home surface.');}
 for(const p of data.players){if(!p.fullName?.trim())add('player '+p.id,'Full name is required.');if(p.dob&&!dateValid(p.dob))add('player '+p.id,'Invalid date of birth.');}
 for(const s of data.seasons){const p=`season ${s.id}`,rules=rulesFor(data,s.id);if(!dateValid(s.startDate)||!dateValid(s.endDate)||s.startDate>s.endDate)add(p,'Season dates must be valid and ordered.');
 if(!Array.isArray(s.teamIds)||new Set(s.teamIds).size!==s.teamIds?.length)add(p,'Season teams must be a unique array.');for(const id of s.teamIds||[])if(!maps.teams.has(id))add(p,`Unknown team ${id}.`);
 if(s.teamIds?.length!==rules.teamCount)warn(p,`Expected ${rules.teamCount} teams; currently ${s.teamIds?.length||0}.`);
 for(const [k,v] of Object.entries({rosterSize:rules.rosterSize,squadSize:rules.squadSize,singlesRubbers:rules.singlesRubbers,doublesRubbers:rules.doublesRubbers,regularSeasonRounds:rules.regularSeasonRounds,finalsTeams:rules.finalsTeams}))if(!Number.isInteger(v)||v<=0)add(p,`${k} must be a positive integer.`);
 if(rules.squadSize>rules.rosterSize)add(p,'Squad size exceeds full roster size.');
 if(Object.values(rules.rosterSlots).reduce((a,b)=>a+b,0)!==rules.rosterSize)add(p,'Classification slot counts must sum to roster size.');
 if(rules.doublesUseWholeSquad&&rules.doublesRubbers*2!==rules.squadSize)add(p,'Four pairs must collectively use the full squad under current rules.');
 if(!['manual'].includes(rules.finals.exactTie))add(p,'Only manual Finals deciding procedure is currently implemented.');
 for(const v of Object.values(rules.points))if(!Number.isFinite(v))add(p,'Race Points must be finite numbers.');
 for(const key of rules.standingsTiebreaks)if(!['points','rubberDiff','setDiff','gameDiff','wins','setsFor','gamesFor','rubbersFor'].includes(key))add(p,`Unsupported standings tiebreak: ${key}.`);
 for(const k of ['scale','halfLifeDays','l2','displayScale'])if(!(rules.rating[k]>0))add(p,`Rating ${k} must be positive.`);
 if(s.finals?.cycle){const c=s.finals.cycle;if(!c.hostA?.city||!c.hostB?.city||!Number.isInteger(c.startYear)||!Number.isInteger(c.endYear)||c.endYear!==c.startYear+1||s.year<c.startYear||s.year>c.endYear)add(p,'Finals requires a valid two-year host cycle with Host A and B.');}
 if(s.finals?.seeds&&(s.finals.seeds.length!==rules.finalsTeams||new Set(s.finals.seeds).size!==rules.finalsTeams||s.finals.seeds.some(id=>!s.teamIds.includes(id))))add(p,'Finals seeds must contain the unique qualified teams.');
 }
 const overlap=(a,b)=>!(a.endDate&&b.startDate&&a.endDate<b.startDate||b.endDate&&a.startDate&&b.endDate<a.startDate);
 for(const [i,r] of data.rosters.entries()){const p=`rosters[${i}]`,s=maps.seasons.get(r.seasonId),rules=rulesFor(data,r.seasonId);if(!s)add(p,'Unknown season.');if(!maps.teams.has(r.teamId)||!s?.teamIds?.includes(r.teamId))add(p,'Team is not registered for this season.');if(!maps.players.has(r.playerId))add(p,`Unknown player ${r.playerId}.`);if(!rules.classifications[r.classification])add(p,'Classification must be a configured career type.');if(!Number.isInteger(r.rosterPosition)||r.rosterPosition<1||r.rosterPosition>rules.rosterSize)add(p,`Roster order must be 1–${rules.rosterSize}.`);
 for(const key of ['startDate','endDate'])if(r[key]&&!dateValid(r[key]))add(p,`Invalid ${key}.`);if(r.startDate&&r.endDate&&r.startDate>r.endDate)add(p,'Registration date range is reversed.');
 for(const q of data.rosters.slice(0,i).filter(q=>q.seasonId===r.seasonId)){if(q.playerId===r.playerId&&(!rules.allowTransfers||overlap(q,r)))add(p,'Player is registered twice in the same season.');if(q.teamId===r.teamId&&q.rosterPosition===r.rosterPosition&&overlap(q,r))add(p,'Duplicate roster position.');}}
 for(const s of data.seasons)for(const id of s.teamIds||[]){const rs=rosterFor(data,s.id,id,s.startDate),rules=rulesFor(data,s.id);if(rs.length!==rules.rosterSize)warn(`${s.id}/${id}`,`Full roster has ${rs.length} of ${rules.rosterSize} players.`);else for(const [role,n] of Object.entries(rules.rosterSlots))if(rs.filter(r=>r.classification===role).length!==n)add(`${s.id}/${id}`,`Roster requires ${n} [${role}] players.`);}
 const matchups=new Set(),roundTeams=new Set(),bracketSlots=new Set();
 for(const raw of data.fixtures){const f=fixtureDefaults(data,raw),p=`fixture ${f.id}`,s=maps.seasons.get(f.seasonId),rules=rulesFor(data,f.seasonId);
 if(!s){add(p,'Unknown season.');continue;}if(!['regular','quarterfinal','semifinal','final'].includes(f.stage))add(p,'Unknown competition stage.');if(!['scheduled','in-progress','completed','postponed','cancelled'].includes(f.status))add(p,'Unknown fixture status.');
 if(!dateValid(f.date)||f.date<s.startDate||f.date>(s.finals?.dates?.final||s.endDate))add(p,'Fixture date is invalid or outside the season.');if(f.stage==='regular'&&f.date>s.endDate)add(p,'Regular fixture is after the regular season end.');
 if(f.homeTeamId===f.awayTeamId)add(p,'Home and away teams must be different.');for(const id of [f.homeTeamId,f.awayTeamId])if(!s.teamIds.includes(id)||!maps.teams.has(id))add(p,`Unknown or unregistered team ${id}.`);
 if(f.surface&&!rules.surfaces[f.surface])add(p,'Unknown surface.');if(f.status==='completed'&&!f.surface)add(p,'Completed fixture needs a surface.');if(f.status==='completed'&&!f.venue)add(p,'Completed fixture needs a venue.');
 if(f.stage!=='regular'){const slotKey=`${f.seasonId}/${f.stage}/${f.bracketSlot}`;if(bracketSlots.has(slotKey))add(p,'Duplicate Finals bracket slot.');bracketSlots.add(slotKey);if(!rules.finals.surfaces.includes(f.surface))add(p,'Finals must use Hard or Indoor Hard.');if(![s.finals?.cycle?.hostA?.city,s.finals?.cycle?.hostB?.city].includes(f.hostCity))add(p,'Finals fixture must use a registered neutral host city.');if(!f.venue)add(p,'Finals fixture needs a neutral venue.');if(!Number.isInteger(f.bracketSlot)||f.bracketSlot<1||f.bracketSlot>(f.stage==='quarterfinal'?rules.finalsTeams/2:f.stage==='semifinal'?2:1))add(p,'Finals requires a valid bracket slot.');if(f.stage==='final'&&f.hostCity!==finalHost(s,rules)?.city)add(p,'Final host must follow this season’s host-cycle assignment.');}
 if(f.stage==='regular'){if(!Number.isInteger(f.round)||f.round<1||f.round>rules.regularSeasonRounds)add(p,'Invalid regular-season round.');const key=`${s.id}/${f.homeTeamId}/${f.awayTeamId}`;if(matchups.has(key))add(p,'Duplicate regular-season home/away matchup.');matchups.add(key);if(f.status!=='cancelled')for(const id of [f.homeTeamId,f.awayTeamId]){const key=`${s.id}/${f.round}/${id}`;if(roundTeams.has(key))add(p,'Team appears twice in one round.');roundTeams.add(key);}}
 const submitted=f.status==='completed'||(f.rubbers||[]).length>0||Object.values(f.squads||{}).some(x=>x?.length);
 if(!submitted)continue;
 for(const [side,teamId] of [['home',f.homeTeamId],['away',f.awayTeamId]]){const squad=f.squads?.[side]||[],roster=rosterFor(data,f.seasonId,teamId,f.date);if(f.status==='completed'&&roster.length!==rules.rosterSize)add(p,`${side} team needs a complete ${rules.rosterSize}-player roster.`);if(squad.length!==rules.squadSize||new Set(squad).size!==squad.length)add(p,`${side} squad needs exactly ${rules.squadSize} unique players.`);for(const id of squad){const r=roster.find(x=>x.playerId===id);if(!r||!maps.players.has(id))add(p,`${side} player ${id} is not registered to this team on the fixture date.`);else if((r.active===false||maps.players.get(id).active===false)&&!f.registrationOverride)add(p,`Inactive player ${id} requires a registration override.`);}}
 const singles={home:[],away:[]},doubles={home:[],away:[]},nums=new Set();
 if(f.status==='completed'&&(f.rubbers||[]).length!==rules.singlesRubbers+rules.doublesRubbers)add(p,`Completed fixture needs ${rules.singlesRubbers+rules.doublesRubbers} rubbers.`);
 for(const r of f.rubbers||[]){const rp=`${p}/rubber ${r.rubberNumber}`;if(nums.has(r.rubberNumber)||!Number.isInteger(r.rubberNumber)||r.rubberNumber<1||r.rubberNumber>rules.singlesRubbers+rules.doublesRubbers)add(rp,'Invalid or duplicate rubber number.');nums.add(r.rubberNumber);if(r.type!==(r.rubberNumber<=rules.singlesRubbers?'singles':'doubles'))add(rp,'Rubber phase does not match its number.');for(const side of ['home','away']){const ids=r[side+'Players']||[],n=r.type==='singles'?1:2;if(ids.length!==n||new Set(ids).size!==n)add(rp,`${side} requires ${n} unique player(s).`);for(const id of ids)if(!f.squads?.[side]?.includes(id))add(rp,`${id} is not in the selected ${side} squad.`);(r.type==='singles'?singles:doubles)[side].push(...ids);}
 try{const parsed=parseScore(r.score??scoreText(r),r.type,r.status||'completed',r.winner);if(r.matchTiebreak&&JSON.stringify(parsed.matchTiebreak)!==JSON.stringify(r.matchTiebreak))add(rp,'Match tiebreak is inconsistent.');}catch(e){add(rp,e.message);}}
 for(const side of ['home','away']){if(rules.singlesUnique&&new Set(singles[side]).size!==singles[side].length)add(p,`${side} singles player used twice.`);if(rules.doublesUseWholeSquad&&(new Set(doubles[side]).size!==doubles[side].length||(f.status==='completed'&&doubles[side].length!==rules.squadSize)))add(p,`${side} doubles pairs must collectively use each squad member once.`);}
 if(f.manualWinner&&!['home','away'].includes(f.manualWinner))add(p,'Invalid manual winner.');if(f.manualWinner&&(!f.resolutionNote||f.stage==='regular'))add(p,'Manual resolution requires a Finals fixture and an explanation.');
 const result=fixtureResult(f,rules);if(f.manualWinner&&result.decidedBy!=='manual')add(p,'Manual resolution is only allowed for an exact Finals tie.');if(f.status==='completed'&&result.decidedBy==='requires-procedure')warn(p,'ATP Cup Finals fixture requires deciding procedure.');
 }
 for(const s of data.seasons){const rules=rulesFor(data,s.id),fs=data.fixtures.filter(f=>f.seasonId===s.id&&f.stage==='regular'),expected=s.teamIds.length*(s.teamIds.length-1);if(fs.length!==expected)(strictSchedule?add:warn)(`season ${s.id}`,`Regular schedule has ${fs.length} of ${expected} fixtures.`);if(new Set(fs.map(f=>f.round)).size!==rules.regularSeasonRounds)(strictSchedule?add:warn)(`season ${s.id}`,`Schedule should cover ${rules.regularSeasonRounds} rounds.`);}
 if(!errors.length)for(const s of data.seasons){const rules=rulesFor(data,s.id),race=standings(data,s.id),b=finalsBracket(data,s.id,race);if(s.finals?.seeds){if(!b.complete)add('season '+s.id,'Finals seeds cannot be locked before the complete regular schedule is resolved.');for(const id of s.finals.seeds){const t=race.find(t=>t.teamId===id),cut=race[rules.finalsTeams-1];if(t&&cut){for(const key of rules.standingsTiebreaks){if(t[key]>cut[key])break;if(t[key]<cut[key]){add('season '+s.id,'Finals seed references a non-qualified team: '+id);break;}}}}}
 for(const f of data.fixtures.filter(f=>f.seasonId===s.id&&f.stage!=='regular')){const entries=f.stage==='quarterfinal'?b.quarterfinals:f.stage==='semifinal'?b.semifinals:[b.final],slot=entries.find(x=>x.slot===f.bracketSlot);if(f.status==='completed'&&!b.locked)add('fixture '+f.id,'Completed Finals fixture requires resolved qualification seeds.');if(b.locked&&slot&&(slot.home&&slot.home!==f.homeTeamId||slot.away&&slot.away!==f.awayTeamId))add('fixture '+f.id,'Finals teams conflict with bracket progression.');if(f.status==='completed'&&f.stage!=='quarterfinal'&&(!slot?.home||!slot?.away))add('fixture '+f.id,'Both preceding knockout winners must be resolved first.');}}
 return {errors,warnings};
}
export function assertValid(data,options){const report=audit(data,options);if(report.errors.length)throw Error(report.errors.map(e=>`${e.path}: ${e.message}`).join('\n'));return report;}
